// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// IonSelectC
List IonSelectC(double zPercentil, double pPercentil, double fcPercentil, int numPixels, NumericVector SP_Pixels, int numCols, NumericVector massAxis, int numSamples, int nPTestGroups, NumericVector R_pTestGroups, NumericVector ClustersSize, List ClustersPixels, NumericMatrix data, double zeroThreshold);
RcppExport SEXP _rMSIKeyIon_IonSelectC(SEXP zPercentilSEXP, SEXP pPercentilSEXP, SEXP fcPercentilSEXP, SEXP numPixelsSEXP, SEXP SP_PixelsSEXP, SEXP numColsSEXP, SEXP massAxisSEXP, SEXP numSamplesSEXP, SEXP nPTestGroupsSEXP, SEXP R_pTestGroupsSEXP, SEXP ClustersSizeSEXP, SEXP ClustersPixelsSEXP, SEXP dataSEXP, SEXP zeroThresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type zPercentil(zPercentilSEXP);
    Rcpp::traits::input_parameter< double >::type pPercentil(pPercentilSEXP);
    Rcpp::traits::input_parameter< double >::type fcPercentil(fcPercentilSEXP);
    Rcpp::traits::input_parameter< int >::type numPixels(numPixelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type SP_Pixels(SP_PixelsSEXP);
    Rcpp::traits::input_parameter< int >::type numCols(numColsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type massAxis(massAxisSEXP);
    Rcpp::traits::input_parameter< int >::type numSamples(numSamplesSEXP);
    Rcpp::traits::input_parameter< int >::type nPTestGroups(nPTestGroupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R_pTestGroups(R_pTestGroupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ClustersSize(ClustersSizeSEXP);
    Rcpp::traits::input_parameter< List >::type ClustersPixels(ClustersPixelsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type zeroThreshold(zeroThresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(IonSelectC(zPercentil, pPercentil, fcPercentil, numPixels, SP_Pixels, numCols, massAxis, numSamples, nPTestGroups, R_pTestGroups, ClustersSize, ClustersPixels, data, zeroThreshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rMSIKeyIon_IonSelectC", (DL_FUNC) &_rMSIKeyIon_IonSelectC, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_rMSIKeyIon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
